spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hsj
    password: yjhyjh2289!@
    url: jdbc:mysql://localhost:3306/board

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100